# Generated by Django 5.1.5 on 2025-04-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='fr_lc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
