# Generated by Django 5.1.5 on 2025-04-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_flightdetails_fr_lc'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='to_lc',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
