# Generated by Django 5.1.5 on 2025-04-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_flightdetails_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='stop_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
