# Generated by Django 5.1.5 on 2025-04-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_flightdetails_stop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='free_meal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
