# Generated by Django 5.1.5 on 2025-04-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_flightdetails_free_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightdetails',
            name='free_meal',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
