# Generated by Django 5.1.5 on 2025-04-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_flightdetails_free_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='airport_search_element',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
