# Generated by Django 5.1.7 on 2025-04-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_airports_airport_search_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='fl_sl_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
