# Generated by Django 5.1.7 on 2025-04-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_flightdetails_fl_sl_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdetails',
            name='fl_dept_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='fl_durat_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightdetails',
            name='fl_price_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
